import { microsoftLogo, oracleLogo, accentureLogo } from "@assets/index";

export const jobCardInfo = [
  {
    number: "1",
    ratings: "3.5",
    mode: "Remote",
    type: "Internship",
    reviews: "20",
    salary: "₱15,000 per month",
    company: "Microsoft Philippines Inc.",
    title: "Microsoft Student Program",
    description:
      "Dive into the world of tech with Microsoft internships! Gain hands-on experience on real projects across various fields, from coding to design. Explore programs designed for your experience level and learn from industry experts. Visit their Careers website to launch your journey!",
    image: microsoftLogo,
    tags: ["Advanced", "Explore", "Project-Based", "Diverse"],
    location: "BGC, Philippines",
    about:
      "At Microsoft Philippines Inc., we believe in nurturing talent and fostering innovation. Our Microsoft Student Program offers a gateway to the dynamic world of technology. Immerse yourself in a collaborative environment where your ideas are valued and your skills are honed. Join us on a journey of exploration and growth, where every challenge is an opportunity to excel.",
    qualifications: [
      "Proficiency in coding or design (depending on the specific internship)",
      "Strong communication and teamwork skills",
      "Enthusiasm for technology and innovation",
    ],
    benefits: [
      "Hands-on experience on real projects",
      "Learning opportunities from industry experts",
      "Career development and growth prospects",
    ],
  },
  {
    number: "2",
    ratings: "4.2",
    mode: "On-site",
    type: "Full-Time",
    reviews: "13",
    salary: "₱35,000 per month",
    company: "Oracle Philippines Inc.",
    title: "Network Administrator",
    description:
      "Our mission is to help people see data in new ways, discover insights, unlock endless possibilities.",
    image: oracleLogo,
    tags: ["Cloud", "Software", "Software", "Technology"],
    location: "Quezon City, Philippines",
    about:
      "Oracle Philippines Inc. is dedicated to revolutionizing the way data is perceived and utilized. As a Network Administrator, you'll be at the forefront of this transformation, ensuring seamless connectivity and optimal performance. Join our team of visionaries and redefine the boundaries of possibility.",
    qualifications: [
      "Bachelor's degree in Computer Science or related field",
      "Proven experience in network administration",
      "Strong analytical and problem-solving skills",
    ],
    benefits: [
      "Competitive salary and benefits package",
      "Opportunities for professional development and training",
      "Exposure to cutting-edge technologies",
    ],
  },
  {
    number: "3",
    ratings: "3.3",
    mode: "On-site",
    reviews: "15",
    type: "Internship",
    salary: "₱10,000 per month",
    company: "Accenture Philippines Inc.",
    title: "Tech Support",
    description:
      "Become a vital part of our team as a Tech Support specialist, providing efficient solutions and exceptional customer service to resolve hardware and software issues swiftly.",
    image: accentureLogo,
    tags: ["Diverse", "Call Center", "Information Technology"],
    location: "Cubao, Philippines",
    about:
      "At Accenture Philippines Inc., we're committed to delivering exceptional service and driving technological advancement. As a Tech Support specialist, you'll play a pivotal role in providing innovative solutions and unparalleled customer support. Join us in shaping the future of technology and making a meaningful impact.",
    qualifications: [
      "Technical degree or equivalent experience",
      "Prior experience in tech support or customer service",
      "Knowledge of hardware and software troubleshooting",
    ],
    benefits: [
      "Competitive salary and performance incentives",
      "Comprehensive training and development programs",
      "Opportunities for career advancement",
    ],
  },
  {
    number: "4",
    ratings: "3.3",
    mode: "On-site",
    type: "Part-Time",
    reviews: "15",
    salary: "₱15,000 per month",
    company: "Accenture Philippines Inc.",
    title: "RJ 45 Maker",
    description:
      "Join us as an RJ45 Maker where you'll assemble connectors onto Ethernet cables with precision and ensure seamless connectivity for our clients.",
    image: accentureLogo,
    tags: ["Engineer", "Networking", "RJ45", "Hardware"],
    location: "Bulacan, Philippines",
    about:
      "Join the innovative team at Accenture Philippines Inc. and become a crucial contributor to our network infrastructure. As an RJ45 Maker, you'll ensure seamless connectivity by meticulously assembling Ethernet cables. Embark on a rewarding journey where precision meets progress, and together, we'll build a better-connected world.",
    qualifications: [
      "Attention to detail and manual dexterity",
      "Basic understanding of networking concepts",
      "Previous experience in a similar role is a plus",
    ],
    benefits: [
      "Competitive wages and benefits",
      "On-the-job training and skill development",
      "Opportunity to work with cutting-edge technology",
    ],
  },
  {
    number: "5",
    ratings: "3.5",
    mode: "Remote",
    type: "Internship",
    reviews: "20",
    salary: "₱15,000 per month",
    company: "Microsoft Philippines Inc.",
    title: "Microsoft Student Program",
    description:
      "Dive into the world of tech with Microsoft internships! Gain hands-on experience on real projects across various fields, from coding to design. Explore programs designed for your experience level and learn from industry experts. Visit their Careers website to launch your journey!",
    image: microsoftLogo,
    tags: ["Advanced", "Explore", "Project-Based", "Diverse"],
    location: "BGC, Philippines",
    about:
      "At Microsoft Philippines Inc., we believe in nurturing talent and fostering innovation. Our Microsoft Student Program offers a gateway to the dynamic world of technology. Immerse yourself in a collaborative environment where your ideas are valued and your skills are honed. Join us on a journey of exploration and growth, where every challenge is an opportunity to excel.",
    qualifications: [
      "Proficiency in coding or design (depending on the specific internship)",
      "Strong communication and teamwork skills",
      "Enthusiasm for technology and innovation",
    ],
    benefits: [
      "Hands-on experience on real projects",
      "Learning opportunities from industry experts",
      "Career development and growth prospects",
    ],
  },
  {
    number: "6",
    ratings: "4.2",
    mode: "On-site",
    type: "Full-Time",
    reviews: "13",
    salary: "₱35,000 per month",
    company: "Oracle Philippines Inc.",
    title: "Network Administrator",
    description:
      "Our mission is to help people see data in new ways, discover insights, unlock endless possibilities.",
    image: oracleLogo,
    tags: ["Cloud", "Software", "Software", "Technology"],
    location: "Quezon City, Philippines",
    about:
      "Oracle Philippines Inc. is dedicated to revolutionizing the way data is perceived and utilized. As a Network Administrator, you'll be at the forefront of this transformation, ensuring seamless connectivity and optimal performance. Join our team of visionaries and redefine the boundaries of possibility.",
    qualifications: [
      "Bachelor's degree in Computer Science or related field",
      "Proven experience in network administration",
      "Strong analytical and problem-solving skills",
    ],
    benefits: [
      "Competitive salary and benefits package",
      "Opportunities for professional development and training",
      "Exposure to cutting-edge technologies",
    ],
  },
  {
    number: "7",
    ratings: "3.3",
    mode: "On-site",
    reviews: "15",
    type: "Internship",
    salary: "₱10,000 per month",
    company: "Accenture Philippines Inc.",
    title: "Tech Support",
    description:
      "Become a vital part of our team as a Tech Support specialist, providing efficient solutions and exceptional customer service to resolve hardware and software issues swiftly.",
    image: accentureLogo,
    tags: ["Diverse", "Call Center", "Information Technology"],
    location: "Cubao, Philippines",
    about:
      "At Accenture Philippines Inc., we're committed to delivering exceptional service and driving technological advancement. As a Tech Support specialist, you'll play a pivotal role in providing innovative solutions and unparalleled customer support. Join us in shaping the future of technology and making a meaningful impact.",
    qualifications: [
      "Technical degree or equivalent experience",
      "Prior experience in tech support or customer service",
      "Knowledge of hardware and software troubleshooting",
    ],
    benefits: [
      "Competitive salary and performance incentives",
      "Comprehensive training and development programs",
      "Opportunities for career advancement",
    ],
  },
  {
    number: "8",
    ratings: "3.3",
    mode: "On-site",
    type: "Part-Time",
    reviews: "15",
    salary: "₱15,000 per month",
    company: "Accenture Philippines Inc.",
    title: "RJ 45 Maker",
    description:
      "Join us as an RJ45 Maker where you'll assemble connectors onto Ethernet cables with precision and ensure seamless connectivity for our clients.",
    image: accentureLogo,
    tags: ["Engineer", "Networking", "RJ45", "Hardware"],
    location: "Bulacan, Philippines",
    about:
      "Join the innovative team at Accenture Philippines Inc. and become a crucial contributor to our network infrastructure. As an RJ45 Maker, you'll ensure seamless connectivity by meticulously assembling Ethernet cables. Embark on a rewarding journey where precision meets progress, and together, we'll build a better-connected world.",
    qualifications: [
      "Attention to detail and manual dexterity",
      "Basic understanding of networking concepts",
      "Previous experience in a similar role is a plus",
    ],
    benefits: [
      "Competitive wages and benefits",
      "On-the-job training and skill development",
      "Opportunity to work with cutting-edge technology",
    ],
  },
  {
    number: "9",
    ratings: "3.3",
    mode: "On-site",
    type: "Part-Time",
    reviews: "15",
    salary: "₱15,000 per month",
    company: "Accenture Philippines Inc.",
    title: "RJ 45 Maker",
    description:
      "Join us as an RJ45 Maker where you'll assemble connectors onto Ethernet cables with precision and ensure seamless connectivity for our clients.",
    image: accentureLogo,
    tags: ["Engineer", "Networking", "RJ45", "Hardware"],
    location: "Bulacan, Philippines",
    about:
      "Join the innovative team at Accenture Philippines Inc. and become a crucial contributor to our network infrastructure. As an RJ45 Maker, you'll ensure seamless connectivity by meticulously assembling Ethernet cables. Embark on a rewarding journey where precision meets progress, and together, we'll build a better-connected world.",
    qualifications: [
      "Attention to detail and manual dexterity",
      "Basic understanding of networking concepts",
      "Previous experience in a similar role is a plus",
    ],
    benefits: [
      "Competitive wages and benefits",
      "On-the-job training and skill development",
      "Opportunity to work with cutting-edge technology",
    ],
  },
];

export const companyTags = [
  "Technology",
  "Software",
  "Cloud",
  "Networking",
  "Hardware",
  "Call Center",
  "Information Technology",
  "Engineer",
  "Diverse",
  "Advanced",
  "Explore",
  "Project-Based",
  "RJ45",
  "Remote",
  "On-site",
  "Internship",
  "Full-Time",
  "Part-Time",
  "Accenture",
  "Microsoft",
  "Oracle",
  "Philippines",
  "BGC",
  "Quezon City",
  "Cubao",
  "Bulacan",
  "City",
  "Company",
  "Job Title",
  "Location",
  "Tag",
  "Keyword",
];

export const dummyUser = {
  id: 1,
  firstName: "John",
  middleName: "Majestic",
  lastName: "Doe",
  email: "johndoe@mail.com",
  password: "ilovejanedoe",
  birthDate: "1990-01-01",
  gender: "Male",
  phone: "09123456789",
  region: "NCR",
  province: "Metro Manila",
  city: "Quezon City",
  barangay: "Barangay 1",
  address: "Street 1",
  socialLinks: [
    "https://www.linkedin.com/in/johndoe",
    "https://www.github.com/johndoe",
    "https://www.facebook.com/johndoe",
    "https://www.twitter.com/johndoe",
  ],
  coverLetter:
    "I am a passionate individual seeking to make a difference in the world.",
  resume: "Resume-Example.pdf",
  additionalNotes: "I am available for interviews on weekdays after 5 PM.",
};

export const dummyChangelog = [
  {
    version: "1.0.0",
    title: "Initial Release",
    date: "2022-01-01",
    changes: [
      "Added basic user profile",
      "Implemented user authentication",
      "Created job search feature",
    ],
  },
  {
    version: "1.1.0",
    title: "Feature Update",
    date: "2022-02-01",
    changes: [
      "Added job application feature",
      "Improved user experience",
      "Enhanced security measures",
    ],
  },
];

export const evalQuestions = [
  {
    number: 1,
    question:
      "How satisfied are you with the overall performance of the company?",
    veryDissatisfied: "20%",
    dissatisfied: "10%",
    neutral: "5%",
    satisfied: "40%",
    verySatisfied: "25%",
  },
  {
    number: 2,
    question:
      "Did the company meet your expectations in terms of product/service quality?",
    veryDissatisfied: "15%",
    dissatisfied: "5%",
    neutral: "10%",
    satisfied: "40%",
    verySatisfied: "30%",
  },
  {
    number: 3,
    question:
      "Were your concerns and inquiries addressed promptly by the company's customer support?",
    veryDissatisfied: "10%",
    dissatisfied: "5%",
    neutral: "15%",
    satisfied: "40%",
    verySatisfied: "30%",
  },
  {
    number: 4,
    question:
      "How likely are you to recommend the company to others based on your experience?",
    veryDissatisfied: "20%",
    dissatisfied: "10%",
    neutral: "5%",
    satisfied: "40%",
    verySatisfied: "25%",
  },
  {
    number: 5,
    question:
      "How satisfied are you with the overall performance of the company?",
    veryDissatisfied: "20%",
    dissatisfied: "10%",
    neutral: "5%",
    satisfied: "40%",
    verySatisfied: "25%",
  },
  {
    number: 6,
    question:
      "How would you rate the company's commitment to ethical business practices?",
    veryDissatisfied: "20%",
    dissatisfied: "10%",
    neutral: "5%",
    satisfied: "40%",
    verySatisfied: "25%",
  },
  {
    number: 7,
    question:
      "How satisfied were you with the efficiency and accuracy of the company's delivery/service process?",
    veryDissatisfied: "20%",
    dissatisfied: "10%",
    neutral: "5%",
    satisfied: "40%",
    verySatisfied: "25%",
  },
  {
    number: 8,
    question:
      "How well did the company understand and fulfill your specific needs and requirements?",
    veryDissatisfied: "20%",
    dissatisfied: "10%",
    neutral: "5%",
    satisfied: "40%",
    verySatisfied: "25%",
  },
  {
    number: 9,
    question: "Was the company transparent regarding pricing and policies?",
    veryDissatisfied: "20%",
    dissatisfied: "10%",
    neutral: "5%",
    satisfied: "40%",
    verySatisfied: "25%",
  },
  {
    number: 10,
    question: "Overall, how would you rate your experience with the company?",
    veryDissatisfied: "20%",
    dissatisfied: "10%",
    neutral: "5%",
    satisfied: "40%",
    verySatisfied: "25%",
  },
];

export const indivUser = [
  {
    id: 1,
    name: "Annaliese Osmint",
    date: "11/29/2023",
    email: "aosmint0@globo.com",
  },
  {
    id: 2,
    name: "Grady Avann",
    date: "1/5/2024",
    email: "gavann1@auda.org.au",
  },
  {
    id: 3,
    name: "Corinna Arnaut",
    date: "12/12/2023",
    email: "carnaut2@github.com",
  },
  {
    id: 4,
    name: "Briny Riggert",
    date: "9/26/2023",
    email: "briggert3@reuters.com",
  },
  {
    id: 5,
    name: "Wallie Duprey",
    date: "11/21/2023",
    email: "wduprey4@jugem.jp",
  },
  {
    id: 6,
    name: "Chrissie Cressy",
    date: "2/20/2024",
    email: "ccressy5@springer.com",
  },
  {
    id: 7,
    name: "Lovell Larman",
    date: "5/5/2024",
    email: "llarman6@t.co",
  },
  {
    id: 8,
    name: "Evangelia Gathwaite",
    date: "2/25/2024",
    email: "egathwaite7@ed.gov",
  },
  {
    id: 9,
    name: "Angie Novik",
    date: "5/18/2024",
    email: "anovik8@themeforest.net",
  },
  {
    id: 10,
    name: "Sergeant Wildsmith",
    date: "11/5/2023",
    email: "swildsmith9@slate.com",
  },
  {
    id: 11,
    name: "Cherilyn Branton",
    date: "2/22/2024",
    email: "cbrantona@ovh.net",
  },
  {
    id: 12,
    name: "Dmitri Bristoe",
    date: "12/9/2023",
    email: "dbristoeb@usa.gov",
  },
  {
    id: 13,
    name: "Griswold Verduin",
    date: "5/20/2024",
    email: "gverduinc@berkeley.edu",
  },
  {
    id: 14,
    name: "Rice Mahoney",
    date: "9/29/2023",
    email: "rmahoneyd@oakley.com",
  },
  {
    id: 15,
    name: "Nicholle Cordaroy",
    date: "3/26/2024",
    email: "ncordaroye@samsung.com",
  },
  {
    id: 16,
    name: "Fritz Corneil",
    date: "5/8/2024",
    email: "fcorneilf@usnews.com",
  },
  {
    id: 17,
    name: "Ricardo Purselow",
    date: "11/18/2023",
    email: "rpurselowg@yahoo.com",
  },
  {
    id: 18,
    name: "Maggee Rays",
    date: "9/8/2023",
    email: "mraysh@examiner.com",
  },
  {
    id: 19,
    name: "June Gyrgorcewicx",
    date: "2/15/2024",
    email: "jgyrgorcewicxi@wix.com",
  },
  {
    id: 20,
    name: "Obie Jaeggi",
    date: "10/11/2023",
    email: "ojaeggij@bizjournals.com",
  },
  {
    id: 21,
    name: "Chastity Roder",
    date: "10/28/2023",
    email: "croderk@163.com",
  },
  {
    id: 22,
    name: "Shem Taberer",
    date: "8/18/2023",
    email: "stabererl@hubpages.com",
  },
  {
    id: 23,
    name: "Timmie Andover",
    date: "12/29/2023",
    email: "tandoverm@eventbrite.com",
  },
  {
    id: 24,
    name: "Corney Crimin",
    date: "11/27/2023",
    email: "ccriminn@stanford.edu",
  },
  {
    id: 25,
    name: "Lin Adamides",
    date: "6/22/2023",
    email: "ladamideso@senate.gov",
  },
  {
    id: 26,
    name: "Ruttger Kidder",
    date: "10/19/2023",
    email: "rkidderp@tinyurl.com",
  },
  {
    id: 27,
    name: "Mercy Filoniere",
    date: "6/20/2023",
    email: "mfiloniereq@abc.net.au",
  },
  {
    id: 28,
    name: "Margi Babbe",
    date: "9/21/2023",
    email: "mbabber@latimes.com",
  },
  {
    id: 29,
    name: "Johnna Hewins",
    date: "8/19/2023",
    email: "jhewinss@google.nl",
  },
  {
    id: 30,
    name: "Jammal Penni",
    date: "11/17/2023",
    email: "jpennit@fotki.com",
  },
  {
    id: 31,
    name: "Brew Sheen",
    date: "6/1/2024",
    email: "bsheenu@sitemeter.com",
  },
  {
    id: 32,
    name: "Butch Gearing",
    date: "12/23/2023",
    email: "bgearingv@livejournal.com",
  },
  {
    id: 33,
    name: "Elana Ruff",
    date: "5/9/2024",
    email: "eruffw@techcrunch.com",
  },
  {
    id: 34,
    name: "Lucie Lound",
    date: "2/5/2024",
    email: "lloundx@unblog.fr",
  },
  {
    id: 35,
    name: "Akim MacTrustram",
    date: "9/3/2023",
    email: "amactrustramy@youtube.com",
  },
  {
    id: 36,
    name: "Rina Marsay",
    date: "12/14/2023",
    email: "rmarsayz@mail.ru",
  },
  {
    id: 37,
    name: "Jandy Donegan",
    date: "5/22/2024",
    email: "jdonegan10@123-reg.co.uk",
  },
  {
    id: 38,
    name: "Angelique Leverette",
    date: "5/25/2024",
    email: "aleverette11@cdbaby.com",
  },
  {
    id: 39,
    name: "Bran Le Sieur",
    date: "2/18/2024",
    email: "ble12@yale.edu",
  },
  {
    id: 40,
    name: "Stinky Alam",
    date: "9/21/2023",
    email: "salam13@reverbnation.com",
  },
  {
    id: 41,
    name: "Margareta Littleton",
    date: "12/7/2023",
    email: "mlittleton14@google.fr",
  },
  {
    id: 42,
    name: "Fabien Heintsch",
    date: "2/21/2024",
    email: "fheintsch15@friendfeed.com",
  },
  {
    id: 43,
    name: "Lorrin Muirden",
    date: "1/14/2024",
    email: "lmuirden16@cnbc.com",
  },
  {
    id: 44,
    name: "Brig Knock",
    date: "5/8/2024",
    email: "bknock17@harvard.edu",
  },
  {
    id: 45,
    name: "Lorry Blenkin",
    date: "12/29/2023",
    email: "lblenkin18@slashdot.org",
  },
  {
    id: 46,
    name: "Nikolos Hauxley",
    date: "2/29/2024",
    email: "nhauxley19@washington.edu",
  },
  {
    id: 47,
    name: "Wilma Decroix",
    date: "5/21/2024",
    email: "wdecroix1a@lulu.com",
  },
  {
    id: 48,
    name: "Davidson Daintree",
    date: "1/9/2024",
    email: "ddaintree1b@cdc.gov",
  },
  {
    id: 49,
    name: "Erastus Sabin",
    date: "11/3/2023",
    email: "esabin1c@tiny.cc",
  },
  {
    id: 50,
    name: "Pyotr Botright",
    date: "5/13/2024",
    email: "pbotright1d@freewebs.com",
  },
];

export const employeeTable = [
  {
    id: 1,
    first_name: "Blanche",
    last_name: "Branscombe",
    job: "Dental Hygienist",
    email: "bbranscombe0@bbb.org",
  },
  {
    id: 2,
    first_name: "Kacy",
    last_name: "Schachter",
    job: "Help Desk Technician",
    email: "kschachter1@live.com",
  },
  {
    id: 3,
    first_name: "Henka",
    last_name: "Smallthwaite",
    job: "Financial Analyst",
    email: "hsmallthwaite2@mediafire.com",
  },
  {
    id: 4,
    first_name: "Simeon",
    last_name: "Few",
    job: "Pharmacist",
    email: "sfew3@dailymail.co.uk",
  },
  {
    id: 5,
    first_name: "Olenka",
    last_name: "Fortnam",
    job: "Technical Writer",
    email: "ofortnam4@usgs.gov",
  },
  {
    id: 6,
    first_name: "Leandra",
    last_name: "McNuff",
    job: "Cost Accountant",
    email: "lmcnuff5@aboutads.info",
  },
  {
    id: 7,
    first_name: "Mariette",
    last_name: "Leathard",
    job: "Research Assistant III",
    email: "mleathard6@nationalgeographic.com",
  },
  {
    id: 8,
    first_name: "Valida",
    last_name: "Munnion",
    job: "Geologist II",
    email: "vmunnion7@cnet.com",
  },
  {
    id: 9,
    first_name: "Dayna",
    last_name: "Brekonridge",
    job: "Editor",
    email: "dbrekonridge8@chicagotribune.com",
  },
  {
    id: 10,
    first_name: "Cristionna",
    last_name: "Kees",
    job: "Assistant Manager",
    email: "ckees9@wikipedia.org",
  },
  {
    id: 11,
    first_name: "Ninnette",
    last_name: "Pogue",
    job: "Legal Assistant",
    email: "npoguea@cbslocal.com",
  },
  {
    id: 12,
    first_name: "Merna",
    last_name: "Slimon",
    job: "Nurse",
    email: "mslimonb@businessinsider.com",
  },
  {
    id: 13,
    first_name: "Windy",
    last_name: "Parfett",
    job: "General Manager",
    email: "wparfettc@amazonaws.com",
  },
  {
    id: 14,
    first_name: "Adolph",
    last_name: "Minget",
    job: "Cost Accountant",
    email: "amingetd@posterous.com",
  },
  {
    id: 15,
    first_name: "Elinor",
    last_name: "Smalles",
    job: "Community Outreach Specialist",
    email: "esmallese@plala.or.jp",
  },
  {
    id: 16,
    first_name: "Matthus",
    last_name: "Triggle",
    job: "Technical Writer",
    email: "mtrigglef@netlog.com",
  },
  {
    id: 17,
    first_name: "Lou",
    last_name: "Lamy",
    job: "Compensation Analyst",
    email: "llamyg@home.pl",
  },
  {
    id: 18,
    first_name: "Modesta",
    last_name: "Boakes",
    job: "Information Systems Manager",
    email: "mboakesh@yelp.com",
  },
  {
    id: 19,
    first_name: "Mar",
    last_name: "Caunt",
    job: "Office Assistant I",
    email: "mcaunti@squidoo.com",
  },
  {
    id: 20,
    first_name: "Augustine",
    last_name: "Glazyer",
    job: "Systems Administrator III",
    email: "aglazyerj@skype.com",
  },
  {
    id: 21,
    first_name: "Winona",
    last_name: "Houlworth",
    job: "Software Test Engineer IV",
    email: "whoulworthk@edublogs.org",
  },
  {
    id: 22,
    first_name: "Giselle",
    last_name: "Garling",
    job: "Automation Specialist I",
    email: "ggarlingl@wunderground.com",
  },
  {
    id: 23,
    first_name: "Filberto",
    last_name: "Wollacott",
    job: "Programmer Analyst III",
    email: "fwollacottm@whitehouse.gov",
  },
  {
    id: 24,
    first_name: "Sunny",
    last_name: "Edess",
    job: "Software Consultant",
    email: "sedessn@a8.net",
  },
  {
    id: 25,
    first_name: "Merla",
    last_name: "Oneal",
    job: "Executive Secretary",
    email: "monealo@sohu.com",
  },
  {
    id: 26,
    first_name: "Yankee",
    last_name: "Abbotts",
    job: "Business Systems Development Analyst",
    email: "yabbottsp@cnn.com",
  },
  {
    id: 27,
    first_name: "Skip",
    last_name: "Foltin",
    job: "Senior Editor",
    email: "sfoltinq@time.com",
  },
  {
    id: 28,
    first_name: "Corney",
    last_name: "Kobsch",
    job: "Cost Accountant",
    email: "ckobschr@naver.com",
  },
  {
    id: 29,
    first_name: "Juliane",
    last_name: "Caban",
    job: "Chief Design Engineer",
    email: "jcabans@narod.ru",
  },
  {
    id: 30,
    first_name: "Gretel",
    last_name: "Bezemer",
    job: "Software Consultant",
    email: "gbezemert@nyu.edu",
  },
  {
    id: 31,
    first_name: "Burl",
    last_name: "Caseborne",
    job: "Programmer Analyst II",
    email: "bcaseborneu@barnesandnoble.com",
  },
  {
    id: 32,
    first_name: "Lydie",
    last_name: "Duchesne",
    job: "Budget/Accounting Analyst IV",
    email: "lduchesnev@dailymail.co.uk",
  },
  {
    id: 33,
    first_name: "Juieta",
    last_name: "Alebrooke",
    job: "Administrative Assistant I",
    email: "jalebrookew@geocities.com",
  },
  {
    id: 34,
    first_name: "Kylila",
    last_name: "Fossick",
    job: "Quality Control Specialist",
    email: "kfossickx@bluehost.com",
  },
  {
    id: 35,
    first_name: "Dalli",
    last_name: "Hegge",
    job: "VP Product Management",
    email: "dheggey@comsenz.com",
  },
  {
    id: 36,
    first_name: "Norrie",
    last_name: "Paddefield",
    job: "Business Systems Development Analyst",
    email: "npaddefieldz@psu.edu",
  },
  {
    id: 37,
    first_name: "Kariotta",
    last_name: "Battson",
    job: "Business Systems Development Analyst",
    email: "kbattson10@geocities.com",
  },
  {
    id: 38,
    first_name: "Aurora",
    last_name: "Bonhome",
    job: "Account Representative I",
    email: "abonhome11@shutterfly.com",
  },
  {
    id: 39,
    first_name: "Ali",
    last_name: "Durrant",
    job: "Structural Engineer",
    email: "adurrant12@jimdo.com",
  },
  {
    id: 40,
    first_name: "Thorin",
    last_name: "McMylor",
    job: "Recruiter",
    email: "tmcmylor13@jalbum.net",
  },
  {
    id: 41,
    first_name: "Monique",
    last_name: "Wychard",
    job: "Business Systems Development Analyst",
    email: "mwychard14@foxnews.com",
  },
  {
    id: 42,
    first_name: "Kendra",
    last_name: "Spoole",
    job: "Desktop Support Technician",
    email: "kspoole15@phoca.cz",
  },
  {
    id: 43,
    first_name: "Simonne",
    last_name: "McCormick",
    job: "Payment Adjustment Coordinator",
    email: "smccormick16@e-recht24.de",
  },
  {
    id: 44,
    first_name: "Elaine",
    last_name: "Lutsch",
    job: "Developer IV",
    email: "elutsch17@seesaa.net",
  },
  {
    id: 45,
    first_name: "Leoline",
    last_name: "Blankenship",
    job: "Assistant Media Planner",
    email: "lblankenship18@weather.com",
  },
  {
    id: 46,
    first_name: "Marybelle",
    last_name: "Top",
    job: "Food Chemist",
    email: "mtop19@acquirethisname.com",
  },
  {
    id: 47,
    first_name: "Emelita",
    last_name: "Capper",
    job: "Database Administrator I",
    email: "ecapper1a@comsenz.com",
  },
  {
    id: 48,
    first_name: "Clarence",
    last_name: "Turnock",
    job: "Senior Developer",
    email: "cturnock1b@cbsnews.com",
  },
  {
    id: 49,
    first_name: "Dulciana",
    last_name: "McCullouch",
    job: "Civil Engineer",
    email: "dmccullouch1c@angelfire.com",
  },
  {
    id: 50,
    first_name: "Ilsa",
    last_name: "O' Donohoe",
    job: "Office Assistant II",
    email: "iodonohoe1d@furl.net",
  },
  {
    id: 51,
    first_name: "Desmund",
    last_name: "Pepi",
    job: "Quality Control Specialist",
    email: "dpepi1e@a8.net",
  },
  {
    id: 52,
    first_name: "Yelena",
    last_name: "Bouch",
    job: "VP Quality Control",
    email: "ybouch1f@zdnet.com",
  },
  {
    id: 53,
    first_name: "Nerissa",
    last_name: "Dugan",
    job: "Tax Accountant",
    email: "ndugan1g@addthis.com",
  },
  {
    id: 54,
    first_name: "Arnoldo",
    last_name: "Reedick",
    job: "Senior Quality Engineer",
    email: "areedick1h@123-reg.co.uk",
  },
  {
    id: 55,
    first_name: "Caprice",
    last_name: "Pinnigar",
    job: "Junior Executive",
    email: "cpinnigar1i@eventbrite.com",
  },
  {
    id: 56,
    first_name: "Algernon",
    last_name: "Osgerby",
    job: "Data Coordinator",
    email: "aosgerby1j@amazon.de",
  },
  {
    id: 57,
    first_name: "Sigfrid",
    last_name: "Noddings",
    job: "Teacher",
    email: "snoddings1k@t-online.de",
  },
  {
    id: 58,
    first_name: "Joanne",
    last_name: "Kempe",
    job: "Statistician III",
    email: "jkempe1l@sciencedirect.com",
  },
  {
    id: 59,
    first_name: "Eunice",
    last_name: "Kenford",
    job: "General Manager",
    email: "ekenford1m@illinois.edu",
  },
  {
    id: 60,
    first_name: "Sarene",
    last_name: "Andres",
    job: "Project Manager",
    email: "sandres1n@uol.com.br",
  },
  {
    id: 61,
    first_name: "Nowell",
    last_name: "Bulpitt",
    job: "Internal Auditor",
    email: "nbulpitt1o@nba.com",
  },
  {
    id: 62,
    first_name: "Corliss",
    last_name: "Aimable",
    job: "Statistician III",
    email: "caimable1p@imdb.com",
  },
  {
    id: 63,
    first_name: "Zebulon",
    last_name: "Monget",
    job: "Web Developer IV",
    email: "zmonget1q@lulu.com",
  },
  {
    id: 64,
    first_name: "Calv",
    last_name: "Cranney",
    job: "Software Consultant",
    email: "ccranney1r@seesaa.net",
  },
  {
    id: 65,
    first_name: "Pepi",
    last_name: "Sallowaye",
    job: "Senior Quality Engineer",
    email: "psallowaye1s@blogger.com",
  },
  {
    id: 66,
    first_name: "Jannel",
    last_name: "Lancley",
    job: "Payment Adjustment Coordinator",
    email: "jlancley1t@tamu.edu",
  },
  {
    id: 67,
    first_name: "Law",
    last_name: "Guichard",
    job: "Electrical Engineer",
    email: "lguichard1u@netvibes.com",
  },
  {
    id: 68,
    first_name: "Byram",
    last_name: "Rafe",
    job: "VP Quality Control",
    email: "brafe1v@buzzfeed.com",
  },
  {
    id: 69,
    first_name: "Arturo",
    last_name: "Orrock",
    job: "Web Designer III",
    email: "aorrock1w@myspace.com",
  },
  {
    id: 70,
    first_name: "Drusi",
    last_name: "Woodyeare",
    job: "Recruiting Manager",
    email: "dwoodyeare1x@timesonline.co.uk",
  },
  {
    id: 71,
    first_name: "Farlie",
    last_name: "Duffy",
    job: "Associate Professor",
    email: "fduffy1y@woothemes.com",
  },
  {
    id: 72,
    first_name: "Brittney",
    last_name: "Manoelli",
    job: "VP Product Management",
    email: "bmanoelli1z@issuu.com",
  },
  {
    id: 73,
    first_name: "Susana",
    last_name: "Richemont",
    job: "Accounting Assistant II",
    email: "srichemont20@ucsd.edu",
  },
  {
    id: 74,
    first_name: "Sadie",
    last_name: "Winfindale",
    job: "Data Coordinator",
    email: "swinfindale21@cdc.gov",
  },
  {
    id: 75,
    first_name: "Pris",
    last_name: "Scrimgeour",
    job: "Structural Engineer",
    email: "pscrimgeour22@whitehouse.gov",
  },
  {
    id: 76,
    first_name: "Gayle",
    last_name: "Lesmonde",
    job: "Account Executive",
    email: "glesmonde23@unicef.org",
  },
  {
    id: 77,
    first_name: "Cecelia",
    last_name: "Battman",
    job: "Office Assistant III",
    email: "cbattman24@chronoengine.com",
  },
  {
    id: 78,
    first_name: "Antonino",
    last_name: "Grogono",
    job: "Social Worker",
    email: "agrogono25@liveinternet.ru",
  },
  {
    id: 79,
    first_name: "Orran",
    last_name: "Mundle",
    job: "Account Representative I",
    email: "omundle26@fastcompany.com",
  },
  {
    id: 80,
    first_name: "Quent",
    last_name: "Lilleyman",
    job: "Graphic Designer",
    email: "qlilleyman27@economist.com",
  },
  {
    id: 81,
    first_name: "Ilse",
    last_name: "Plews",
    job: "Professor",
    email: "iplews28@cornell.edu",
  },
  {
    id: 82,
    first_name: "Ewen",
    last_name: "Lawless",
    job: "Legal Assistant",
    email: "elawless29@sogou.com",
  },
  {
    id: 83,
    first_name: "Marilyn",
    last_name: "Hofer",
    job: "Administrative Officer",
    email: "mhofer2a@moonfruit.com",
  },
  {
    id: 84,
    first_name: "Frederico",
    last_name: "Lyard",
    job: "Staff Scientist",
    email: "flyard2b@oracle.com",
  },
  {
    id: 85,
    first_name: "Irma",
    last_name: "Avarne",
    job: "Research Assistant IV",
    email: "iavarne2c@wisc.edu",
  },
  {
    id: 86,
    first_name: "Eddy",
    last_name: "Byne",
    job: "Analog Circuit Design manager",
    email: "ebyne2d@china.com.cn",
  },
  {
    id: 87,
    first_name: "Miguelita",
    last_name: "Jeyness",
    job: "Senior Developer",
    email: "mjeyness2e@ucsd.edu",
  },
  {
    id: 88,
    first_name: "George",
    last_name: "Clive",
    job: "Electrical Engineer",
    email: "gclive2f@fotki.com",
  },
  {
    id: 89,
    first_name: "Gaby",
    last_name: "Volcker",
    job: "Speech Pathologist",
    email: "gvolcker2g@paypal.com",
  },
  {
    id: 90,
    first_name: "Gussie",
    last_name: "Connerly",
    job: "VP Product Management",
    email: "gconnerly2h@un.org",
  },
  {
    id: 91,
    first_name: "Cristian",
    last_name: "Helm",
    job: "Nuclear Power Engineer",
    email: "chelm2i@china.com.cn",
  },
  {
    id: 92,
    first_name: "Dwain",
    last_name: "Hevey",
    job: "Project Manager",
    email: "dhevey2j@blog.com",
  },
  {
    id: 93,
    first_name: "Nerita",
    last_name: "Rackstraw",
    job: "Geologist I",
    email: "nrackstraw2k@google.ca",
  },
  {
    id: 94,
    first_name: "Kristofor",
    last_name: "Matissoff",
    job: "Geologist I",
    email: "kmatissoff2l@dot.gov",
  },
  {
    id: 95,
    first_name: "Abey",
    last_name: "Thompson",
    job: "Database Administrator IV",
    email: "athompson2m@flickr.com",
  },
  {
    id: 96,
    first_name: "Teresita",
    last_name: "Towriss",
    job: "Geological Engineer",
    email: "ttowriss2n@t-online.de",
  },
  {
    id: 97,
    first_name: "Henri",
    last_name: "Houlson",
    job: "Actuary",
    email: "hhoulson2o@merriam-webster.com",
  },
  {
    id: 98,
    first_name: "Emilia",
    last_name: "Record",
    job: "Registered Nurse",
    email: "erecord2p@example.com",
  },
  {
    id: 99,
    first_name: "Gib",
    last_name: "Beswell",
    job: "Associate Professor",
    email: "gbeswell2q@phoca.cz",
  },
  {
    id: 100,
    first_name: "Mari",
    last_name: "Mackiewicz",
    job: "Structural Engineer",
    email: "mmackiewicz2r@t.co",
  },
];

export const companyTable = [
  {
    id: 1,
    status: "Approved",
    company_name: "Kamba",
    email: "kbaldery0@geocities.jp",
    no_of_employees: 17,
    date: "2023-10-29T22:19:35Z",
  },
  {
    id: 2,
    status: "Pending",
    company_name: "Minyx",
    email: "ldanielian1@unesco.org",
    no_of_employees: 49,
    date: "2024-05-23T07:29:19Z",
  },
  {
    id: 3,
    status: "Approved",
    company_name: "Realcube",
    email: "jbaggarley2@tumblr.com",
    no_of_employees: 71,
    date: "2023-06-09T05:30:49Z",
  },
  {
    id: 4,
    status: "Pending",
    company_name: "Omba",
    email: "wteck3@multiply.com",
    no_of_employees: 45,
    date: "2023-12-08T04:06:32Z",
  },
  {
    id: 5,
    status: "Cancelled",
    company_name: "Thoughtbridge",
    email: "ady4@wunderground.com",
    no_of_employees: 22,
    date: "2023-12-24T23:19:48Z",
  },
  {
    id: 6,
    status: "Cancelled",
    company_name: "Buzzshare",
    email: "mconkie5@pen.io",
    no_of_employees: 16,
    date: "2024-04-11T16:33:33Z",
  },
  {
    id: 7,
    status: "Approved",
    company_name: "Livefish",
    email: "mruske6@nbcnews.com",
    no_of_employees: 33,
    date: "2023-08-22T09:47:07Z",
  },
  {
    id: 8,
    status: "Pending",
    company_name: "Roombo",
    email: "anevet7@house.gov",
    no_of_employees: 20,
    date: "2024-01-19T05:30:52Z",
  },
  {
    id: 9,
    status: "Approved",
    company_name: "Vinte",
    email: "aknibbs8@admin.ch",
    no_of_employees: 68,
    date: "2023-06-20T19:16:33Z",
  },
  {
    id: 10,
    status: "Cancelled",
    company_name: "Youtags",
    email: "asackes9@wordpress.org",
    no_of_employees: 72,
    date: "2024-04-14T05:40:29Z",
  },
  {
    id: 11,
    status: "Pending",
    company_name: "Photofeed",
    email: "trawsthornea@wunderground.com",
    no_of_employees: 11,
    date: "2024-01-14T07:38:41Z",
  },
  {
    id: 12,
    status: "Cancelled",
    company_name: "Jabbercube",
    email: "rduffieldb@godaddy.com",
    no_of_employees: 41,
    date: "2023-10-15T11:14:42Z",
  },
  {
    id: 13,
    status: "Cancelled",
    company_name: "Skynoodle",
    email: "ccottisfordc@twitpic.com",
    no_of_employees: 57,
    date: "2023-08-23T16:06:42Z",
  },
  {
    id: 14,
    status: "Approved",
    company_name: "Leexo",
    email: "skentond@cam.ac.uk",
    no_of_employees: 38,
    date: "2024-02-19T20:29:41Z",
  },
  {
    id: 15,
    status: "Pending",
    company_name: "Avaveo",
    email: "aroglieroe@desdev.cn",
    no_of_employees: 13,
    date: "2023-06-10T13:44:13Z",
  },
  {
    id: 16,
    status: "Cancelled",
    company_name: "LiveZ",
    email: "ischuttef@marketwatch.com",
    no_of_employees: 79,
    date: "2023-12-27T10:08:10Z",
  },
  {
    id: 17,
    status: "Pending",
    company_name: "Avavee",
    email: "peasdong@kickstarter.com",
    no_of_employees: 24,
    date: "2023-08-24T15:42:16Z",
  },
  {
    id: 18,
    status: "Cancelled",
    company_name: "Pixope",
    email: "ustelljesh@51.la",
    no_of_employees: 6,
    date: "2024-04-13T11:27:25Z",
  },
  {
    id: 19,
    status: "Cancelled",
    company_name: "Oba",
    email: "cgamoni@comsenz.com",
    no_of_employees: 32,
    date: "2023-06-20T15:30:53Z",
  },
  {
    id: 20,
    status: "Approved",
    company_name: "Feedmix",
    email: "mswadlingj@dedecms.com",
    no_of_employees: 5,
    date: "2024-04-02T15:27:23Z",
  },
  {
    id: 21,
    status: "Pending",
    company_name: "Jayo",
    email: "amaywoodk@comcast.net",
    no_of_employees: 21,
    date: "2024-05-29T06:10:20Z",
  },
  {
    id: 22,
    status: "Approved",
    company_name: "Oyope",
    email: "rosgarbyl@google.ca",
    no_of_employees: 14,
    date: "2024-05-19T18:04:40Z",
  },
  {
    id: 23,
    status: "Cancelled",
    company_name: "Feedspan",
    email: "gguerinm@cnn.com",
    no_of_employees: 86,
    date: "2023-06-16T12:03:28Z",
  },
  {
    id: 24,
    status: "Approved",
    company_name: "Gabcube",
    email: "fenburyn@networkadvertising.org",
    no_of_employees: 70,
    date: "2023-12-04T12:26:08Z",
  },
  {
    id: 25,
    status: "Approved",
    company_name: "Skinte",
    email: "crouso@samsung.com",
    no_of_employees: 57,
    date: "2024-03-09T03:58:36Z",
  },
  {
    id: 26,
    status: "Cancelled",
    company_name: "Muxo",
    email: "jswetmanp@webmd.com",
    no_of_employees: 8,
    date: "2023-10-04T12:11:06Z",
  },
  {
    id: 27,
    status: "Pending",
    company_name: "Tavu",
    email: "aclemasq@narod.ru",
    no_of_employees: 79,
    date: "2023-11-21T19:00:22Z",
  },
  {
    id: 28,
    status: "Cancelled",
    company_name: "Brainsphere",
    email: "ayandler@tinyurl.com",
    no_of_employees: 91,
    date: "2023-10-22T01:45:57Z",
  },
  {
    id: 29,
    status: "Pending",
    company_name: "Linklinks",
    email: "aswyres@nps.gov",
    no_of_employees: 49,
    date: "2024-04-05T11:52:38Z",
  },
  {
    id: 30,
    status: "Approved",
    company_name: "Twitterlist",
    email: "ggammellt@va.gov",
    no_of_employees: 96,
    date: "2023-07-11T09:23:05Z",
  },
  {
    id: 31,
    status: "Cancelled",
    company_name: "Yamia",
    email: "lmcauslandu@weebly.com",
    no_of_employees: 61,
    date: "2023-08-13T17:41:16Z",
  },
  {
    id: 32,
    status: "Approved",
    company_name: "Snaptags",
    email: "btinseyv@biglobe.ne.jp",
    no_of_employees: 75,
    date: "2024-03-21T08:40:27Z",
  },
  {
    id: 33,
    status: "Approved",
    company_name: "Omba",
    email: "ebowcherw@vkontakte.ru",
    no_of_employees: 37,
    date: "2024-02-27T11:29:12Z",
  },
  {
    id: 34,
    status: "Cancelled",
    company_name: "Thoughtmix",
    email: "rcordnerx@artisteer.com",
    no_of_employees: 38,
    date: "2024-04-16T08:50:53Z",
  },
  {
    id: 35,
    status: "Approved",
    company_name: "Youfeed",
    email: "jhumany@cargocollective.com",
    no_of_employees: 63,
    date: "2024-02-22T05:14:23Z",
  },
  {
    id: 36,
    status: "Cancelled",
    company_name: "Feedfire",
    email: "aabramzonz@ted.com",
    no_of_employees: 3,
    date: "2024-04-11T04:12:27Z",
  },
  {
    id: 37,
    status: "Cancelled",
    company_name: "InnoZ",
    email: "ssarginson10@netscape.com",
    no_of_employees: 6,
    date: "2024-03-23T21:18:35Z",
  },
  {
    id: 38,
    status: "Approved",
    company_name: "Babblestorm",
    email: "kseyffert11@patch.com",
    no_of_employees: 65,
    date: "2023-12-17T02:23:42Z",
  },
  {
    id: 39,
    status: "Pending",
    company_name: "Twitterwire",
    email: "bschutte12@latimes.com",
    no_of_employees: 53,
    date: "2024-05-05T20:20:47Z",
  },
  {
    id: 40,
    status: "Approved",
    company_name: "Oyondu",
    email: "dearlam13@vimeo.com",
    no_of_employees: 16,
    date: "2023-10-16T08:00:38Z",
  },
  {
    id: 41,
    status: "Pending",
    company_name: "Shufflester",
    email: "mburgett14@google.fr",
    no_of_employees: 45,
    date: "2024-01-30T05:01:33Z",
  },
  {
    id: 42,
    status: "Pending",
    company_name: "Realbridge",
    email: "ccrayden15@abc.net.au",
    no_of_employees: 71,
    date: "2023-10-01T07:47:30Z",
  },
  {
    id: 43,
    status: "Approved",
    company_name: "Camimbo",
    email: "gioselevich16@yelp.com",
    no_of_employees: 53,
    date: "2023-10-22T13:48:35Z",
  },
  {
    id: 44,
    status: "Pending",
    company_name: "Zoomzone",
    email: "scathie17@un.org",
    no_of_employees: 37,
    date: "2023-07-25T16:51:09Z",
  },
  {
    id: 45,
    status: "Cancelled",
    company_name: "Fanoodle",
    email: "tdavidde18@creativecommons.org",
    no_of_employees: 51,
    date: "2024-05-29T20:28:41Z",
  },
  {
    id: 46,
    status: "Cancelled",
    company_name: "Buzzshare",
    email: "dmotherwell19@symantec.com",
    no_of_employees: 26,
    date: "2023-10-04T11:44:39Z",
  },
  {
    id: 47,
    status: "Pending",
    company_name: "Flipopia",
    email: "rstickford1a@sciencedirect.com",
    no_of_employees: 36,
    date: "2024-05-03T13:25:06Z",
  },
  {
    id: 48,
    status: "Approved",
    company_name: "Flipopia",
    email: "uivantyev1b@springer.com",
    no_of_employees: 13,
    date: "2023-10-12T13:01:37Z",
  },
  {
    id: 49,
    status: "Cancelled",
    company_name: "Myworks",
    email: "sknapton1c@bravesites.com",
    no_of_employees: 56,
    date: "2024-02-07T03:52:32Z",
  },
  {
    id: 50,
    status: "Approved",
    company_name: "Jaxworks",
    email: "ghellwing1d@google.com",
    no_of_employees: 12,
    date: "2024-02-18T03:14:58Z",
  },
  {
    id: 51,
    status: "Cancelled",
    company_name: "Skipstorm",
    email: "gimesen1e@about.me",
    no_of_employees: 55,
    date: "2024-03-04T00:22:35Z",
  },
  {
    id: 52,
    status: "Approved",
    company_name: "Yamia",
    email: "bheadey1f@pagesperso-orange.fr",
    no_of_employees: 60,
    date: "2023-09-10T07:42:38Z",
  },
  {
    id: 53,
    status: "Cancelled",
    company_name: "Gabtune",
    email: "roddey1g@reddit.com",
    no_of_employees: 56,
    date: "2024-04-10T07:15:41Z",
  },
  {
    id: 54,
    status: "Cancelled",
    company_name: "Jetwire",
    email: "kclear1h@google.fr",
    no_of_employees: 60,
    date: "2023-12-20T14:58:45Z",
  },
  {
    id: 55,
    status: "Pending",
    company_name: "Shufflester",
    email: "emeineking1i@ucla.edu",
    no_of_employees: 97,
    date: "2023-08-23T01:26:56Z",
  },
  {
    id: 56,
    status: "Cancelled",
    company_name: "Shuffletag",
    email: "rrumney1j@meetup.com",
    no_of_employees: 13,
    date: "2024-01-25T12:57:26Z",
  },
  {
    id: 57,
    status: "Approved",
    company_name: "Quatz",
    email: "scorck1k@jiathis.com",
    no_of_employees: 87,
    date: "2023-08-19T10:38:08Z",
  },
  {
    id: 58,
    status: "Pending",
    company_name: "Katz",
    email: "itommasi1l@mozilla.org",
    no_of_employees: 10,
    date: "2024-01-17T23:57:15Z",
  },
  {
    id: 59,
    status: "Approved",
    company_name: "Zooveo",
    email: "jmillom1m@weibo.com",
    no_of_employees: 75,
    date: "2023-11-07T16:22:26Z",
  },
  {
    id: 60,
    status: "Approved",
    company_name: "Roomm",
    email: "mfranchi1n@sciencedaily.com",
    no_of_employees: 69,
    date: "2023-06-15T22:38:12Z",
  },
  {
    id: 61,
    status: "Pending",
    company_name: "Voonyx",
    email: "kradnage1o@noaa.gov",
    no_of_employees: 66,
    date: "2024-02-02T11:23:19Z",
  },
  {
    id: 62,
    status: "Pending",
    company_name: "Jetwire",
    email: "mallott1p@ca.gov",
    no_of_employees: 64,
    date: "2023-12-30T01:00:15Z",
  },
  {
    id: 63,
    status: "Approved",
    company_name: "Rhynyx",
    email: "rstobbes1q@webmd.com",
    no_of_employees: 61,
    date: "2023-08-27T01:20:10Z",
  },
  {
    id: 64,
    status: "Pending",
    company_name: "Twitterworks",
    email: "nseelbach1r@addtoany.com",
    no_of_employees: 15,
    date: "2023-09-05T03:37:07Z",
  },
  {
    id: 65,
    status: "Cancelled",
    company_name: "Jabbersphere",
    email: "vdemaria1s@nyu.edu",
    no_of_employees: 87,
    date: "2024-02-09T19:28:46Z",
  },
  {
    id: 66,
    status: "Cancelled",
    company_name: "Realblab",
    email: "lkeslake1t@spotify.com",
    no_of_employees: 75,
    date: "2024-03-31T14:16:45Z",
  },
  {
    id: 67,
    status: "Approved",
    company_name: "Blogpad",
    email: "ibowkett1u@google.pl",
    no_of_employees: 37,
    date: "2023-07-08T10:11:05Z",
  },
  {
    id: 68,
    status: "Approved",
    company_name: "Mudo",
    email: "dwhittington1v@ocn.ne.jp",
    no_of_employees: 6,
    date: "2024-03-29T03:25:20Z",
  },
  {
    id: 69,
    status: "Cancelled",
    company_name: "Ozu",
    email: "djarry1w@wp.com",
    no_of_employees: 11,
    date: "2023-07-06T03:55:19Z",
  },
  {
    id: 70,
    status: "Pending",
    company_name: "Aimbo",
    email: "tchittenden1x@nsw.gov.au",
    no_of_employees: 69,
    date: "2024-03-10T09:44:35Z",
  },
  {
    id: 71,
    status: "Approved",
    company_name: "Jabberstorm",
    email: "dbutchard1y@squarespace.com",
    no_of_employees: 21,
    date: "2023-06-14T00:22:59Z",
  },
  {
    id: 72,
    status: "Approved",
    company_name: "Tambee",
    email: "grubinfeld1z@artisteer.com",
    no_of_employees: 95,
    date: "2024-01-29T01:57:17Z",
  },
  {
    id: 73,
    status: "Pending",
    company_name: "Dabfeed",
    email: "arabjohn20@sfgate.com",
    no_of_employees: 62,
    date: "2024-01-22T05:07:09Z",
  },
  {
    id: 74,
    status: "Cancelled",
    company_name: "Ailane",
    email: "llimmer21@accuweather.com",
    no_of_employees: 69,
    date: "2024-04-10T20:13:21Z",
  },
  {
    id: 75,
    status: "Cancelled",
    company_name: "Janyx",
    email: "bdemsey22@ustream.tv",
    no_of_employees: 73,
    date: "2024-05-13T23:24:20Z",
  },
  {
    id: 76,
    status: "Cancelled",
    company_name: "Einti",
    email: "hreeme23@pbs.org",
    no_of_employees: 65,
    date: "2023-10-13T21:46:03Z",
  },
  {
    id: 77,
    status: "Approved",
    company_name: "Realcube",
    email: "elelliott24@nifty.com",
    no_of_employees: 79,
    date: "2023-12-20T13:21:54Z",
  },
  {
    id: 78,
    status: "Cancelled",
    company_name: "Flipstorm",
    email: "dfeasley25@163.com",
    no_of_employees: 45,
    date: "2023-07-08T16:31:54Z",
  },
  {
    id: 79,
    status: "Pending",
    company_name: "Voonder",
    email: "cbilam26@imgur.com",
    no_of_employees: 66,
    date: "2023-09-19T01:03:30Z",
  },
  {
    id: 80,
    status: "Pending",
    company_name: "Fatz",
    email: "aiacivelli27@wsj.com",
    no_of_employees: 36,
    date: "2023-08-26T22:36:30Z",
  },
  {
    id: 81,
    status: "Pending",
    company_name: "Jamia",
    email: "vbagley28@simplemachines.org",
    no_of_employees: 98,
    date: "2024-04-05T16:53:52Z",
  },
  {
    id: 82,
    status: "Approved",
    company_name: "Zoozzy",
    email: "mvansalzberger29@ning.com",
    no_of_employees: 8,
    date: "2023-11-07T01:13:55Z",
  },
  {
    id: 83,
    status: "Pending",
    company_name: "Jabbercube",
    email: "tfrost2a@prnewswire.com",
    no_of_employees: 39,
    date: "2023-09-14T03:45:34Z",
  },
  {
    id: 84,
    status: "Approved",
    company_name: "Lajo",
    email: "cmcgorley2b@hostgator.com",
    no_of_employees: 12,
    date: "2024-01-03T20:28:13Z",
  },
  {
    id: 85,
    status: "Cancelled",
    company_name: "Photospace",
    email: "ewriter2c@usatoday.com",
    no_of_employees: 50,
    date: "2024-01-17T23:07:35Z",
  },
  {
    id: 86,
    status: "Cancelled",
    company_name: "Cogidoo",
    email: "csnailham2d@sakura.ne.jp",
    no_of_employees: 88,
    date: "2024-01-18T18:15:16Z",
  },
  {
    id: 87,
    status: "Cancelled",
    company_name: "Gabcube",
    email: "dspeere2e@tmall.com",
    no_of_employees: 6,
    date: "2024-02-24T10:28:39Z",
  },
  {
    id: 88,
    status: "Cancelled",
    company_name: "Topicblab",
    email: "ddubock2f@mozilla.org",
    no_of_employees: 5,
    date: "2023-08-29T12:15:16Z",
  },
  {
    id: 89,
    status: "Approved",
    company_name: "Skimia",
    email: "bgriffoen2g@netscape.com",
    no_of_employees: 53,
    date: "2023-11-23T17:19:22Z",
  },
  {
    id: 90,
    status: "Approved",
    company_name: "Shuffletag",
    email: "mnortheast2h@telegraph.co.uk",
    no_of_employees: 96,
    date: "2023-09-04T02:18:21Z",
  },
  {
    id: 91,
    status: "Approved",
    company_name: "Edgepulse",
    email: "rbatson2i@odnoklassniki.ru",
    no_of_employees: 43,
    date: "2023-10-04T01:02:31Z",
  },
  {
    id: 92,
    status: "Pending",
    company_name: "Linkbuzz",
    email: "nciccone2j@facebook.com",
    no_of_employees: 90,
    date: "2023-07-04T19:03:22Z",
  },
  {
    id: 93,
    status: "Approved",
    company_name: "Skipstorm",
    email: "tbowgen2k@ucoz.com",
    no_of_employees: 70,
    date: "2023-09-12T14:57:04Z",
  },
  {
    id: 94,
    status: "Cancelled",
    company_name: "Vipe",
    email: "gcullerne2l@cdbaby.com",
    no_of_employees: 36,
    date: "2023-11-27T16:24:37Z",
  },
  {
    id: 95,
    status: "Cancelled",
    company_name: "Eimbee",
    email: "mthreadgold2m@issuu.com",
    no_of_employees: 23,
    date: "2024-02-15T17:08:04Z",
  },
  {
    id: 96,
    status: "Cancelled",
    company_name: "Quatz",
    email: "mreddy2n@xing.com",
    no_of_employees: 12,
    date: "2023-11-16T20:52:07Z",
  },
  {
    id: 97,
    status: "Approved",
    company_name: "Quimba",
    email: "lmcquillan2o@hc360.com",
    no_of_employees: 54,
    date: "2023-08-09T02:07:38Z",
  },
  {
    id: 98,
    status: "Cancelled",
    company_name: "Jazzy",
    email: "ascrange2p@com.com",
    no_of_employees: 3,
    date: "2023-12-11T14:34:38Z",
  },
  {
    id: 99,
    status: "Pending",
    company_name: "Oozz",
    email: "bdiboll2q@skype.com",
    no_of_employees: 5,
    date: "2024-03-16T20:06:22Z",
  },
  {
    id: 100,
    status: "Approved",
    company_name: "Fiveclub",
    email: "kbrearty2r@bloomberg.com",
    no_of_employees: 64,
    date: "2023-08-16T05:03:43Z",
  },
];
