import { Rubik } from "next/font/google";
import "./globals.css";
// import NavBar from "./customComp/NavBar";
import localFont from "next/font/local"

const rubik = Rubik({ subsets: ["latin"] });

const myFont = localFont({ src: '../fonts/digital-7.ttf' })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        {/* <NavBar /> */}
        {children}      
      </body>
    </html>
  );
}
